name: smart_parking_lot
description: A new Flutter project.

# `flutter pub publish`
publish_to: "none"

# https://developer.android.com/studio/publish/versioning
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3

environment:
  sdk: ">=2.17.6 <3.0.0"

# flutter pub upgrade --major-versions
# flutter pub outdated
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  package_info_plus: ^1.4.3+1
  easy_localization: ^3.0.1
  dynamic_color: ^1.5.4
  google_fonts: ^3.0.1
  adaptive_dialog: ^1.8.0+1
  flutter_secure_storage: ^6.0.0
  shared_preferences: ^2.0.15
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  responsive_builder: ^0.4.3
  flutter_signin_button: ^2.0.0
  sign_in_with_apple: ^4.1.0
  google_sign_in: ^5.4.1
  firebase_auth_platform_interface: ^6.6.0
  flutter_phoenix: ^1.1.0
  cached_network_image: ^3.2.2
  cloud_firestore: ^3.4.6
  copy_with_extension: ^4.0.3
  json_annotation: ^4.6.0
  swipeable_page_route: ^0.2.6
  firebase_storage: ^10.3.8
  path_provider: ^2.0.11
  simple_shadow: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # configure in analysis_options.yaml
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  copy_with_extension_gen: ^4.0.3

# https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/logo/
    - assets/lot/

  # https://flutter.dev/assets-and-images/#resolution-aware
  # https://flutter.dev/assets-and-images/#from-packages

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
